spring:
  #数据源
  datasource:
    url: jdbc:mysql://192.168.145.132:3306/mybatis_plus_demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: canal
    password: canal
    driver-class-name: com.mysql.cj.jdbc.Driver

